# Generated by Django 3.2.16 on 2022-11-13 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20221113_1522'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesstype',
            options={},
        ),
    ]
