# Generated by Django 3.2 on 2022-11-21 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userprofiles', '0001_initial'),
        ('checkout', '0002_auto_20221121_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account', to='userprofiles.profile'),
        ),
    ]
